-- Create a table to store analytics data
create table analytics (
  id bigint generated by default as identity primary key,
  event_type text not null, -- 'page_view' or 'click'
  path text,                -- The URL path
  meta jsonb,               -- Extra data like coordinates or element details
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- (Optional) Enable Row Level Security if you want to restrict reads
alter table analytics enable row level security;

-- Allow anonymous inserts (adjust policy as needed for your security model)
create policy "Allow public inserts" on analytics for insert with check (true);
